---
  - name: create a security group for instance
    hosts: localhost
    tasks:
      - name: Setting up the Security Group for new instance
        ec2_group:
          name: Group_AWS
          description: Allowing Traffic on port 22 and 80
          region: ap-south-1
          aws_access_key: AKIASZJWJOYGT54NYPJA
          aws_secret_key: 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
          rules:
           - proto: tcp
             from_port: 80
             to_port: 80
             cidr_ip: 0.0.0.0/0

           - proto: tcp
             from_port: 22
             to_port: 22
             cidr_ip: 0.0.0.0/0

           - proto: icmp
             from_port: -1
             to_port: -1
             cidr_ip: 0.0.0.0/0
          rules_egress:
           - proto: all
             cidr_ip: 0.0.0.0/0
          vpc_id: vpc-064f6bd87cb26784e
